version: '3.8'

services:
  app1:
    image: poll_app
    build:
      context: .
    container_name: poll_app1
    ports:
      - '3005:${PORT}'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  app2:
    image: poll_app
    build:
      context: .
    container_name: poll_app2
    ports:
      - '3008:${PORT}'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
volumes:
  polling-storage:
